#!/bin/bash -x

# current CUDA generation
NVDRVVER=390.25
CUDNNVER=7
CUDAMAJ=9
CUDAMIN=0
CUDAREV=103
CUDATOP=${CUDAMAJ}.${CUDAMIN}
CUDAVER=${CUDATOP}.${CUDAREV}
CUDAKERN=390.25


export KV=`dpkg -l  | grep linux-image- | grep -v meta | perl -lane 'print $F[1] =~ /linux-image-(.*)/'`
export KSV=`echo ${KV} | perl -lane 'printf $F[0] =~ /^(\d+\.\d+)/'`

echo KSV = ${KSV}
KP=/usr/src/linux-source-${KSV}
echo KP = ${KP}

# 1st install NVidia driver

chmod +x NVIDIA-Linux-x86_64-${NVDRVVER}.run
sh ./NVIDIA-Linux-x86_64-${NVDRVVER}.run -a -q --no-rpms --no-backup --no-x-check --opengl-headers --kernel-source-path=${KP} -k ${KV} --no-nvidia-modprobe --ui=none
#

# 2nd install cuda, old one first, then new one
chmod +x cuda_${CUDAVER}_${CUDAKERN}_linux.run
sh ./cuda_${CUDAVER}_${CUDAKERN}_linux.run --silent --toolkit --samples --verbose 

# 3rd install cudnn, old one first, then new one
tar -zxf cudnn-${CUDATOP}-linux-x64-v${CUDNNVER}.tgz  -C /usr/local/cuda-${CUDATOP}

# 4th generate an /etc/profile.d/cuda.sh
cat >/etc/profile.d/cuda.sh<<EOF1
CUDA_REV=${CUDATOP}
export CUDA_HOME=/usr/local/cuda-\${CUDA_REV}
export PATH=\$PATH:\$CUDA_HOME/bin
export LD_LIBRARY_PATH=\$CUDA_HOME/lib64:\${LD_LIBRARY_PATH:+:\${LD_LIBRARY_PATH}}
EOF1

chmod 0755 /etc/profile.d/cuda.sh

# 5th generate an /etc/ld.so.conf.d/cuda.conf
cat >/etc/ld.so.conf.d/cuda.conf<<EOF2
/usr/local/cuda-${CUDATOP}/lib64
/usr/local/cuda-${CUDATOP}/libnvvp
/usr/local/cuda-${CUDATOP}/libnsight
/usr/local/cuda-${OLD_CUDATOP}/lib64
/usr/local/cuda-${OLD_CUDATOP}/libnvvp
/usr/local/cuda-${OLD_CUDATOP}/libnsight
EOF2

ldconfig -v

# 6th clean up extraneous stuff (docs, etc.)
rm -rf /usr/local/cuda-9.0/doc/pdf /usr/local/cuda-9.0/doc/html
#
# get rid of static libraries, should not be needed
rm -rf /usr/local/cuda-9.0/lib64/*static.a
#
# samples ...
rm -rf /usr/local/cuda-9.0/samples


