#!/bin/bash -x

INSTALL_DRIVER=0
INSTALL_FIRMWARE=1

# Chelsio driver info
CHELSIO_REV=3.7.1.0
CHELSIO=ChelsioUwire-${CHELSIO_REV}
CHELSIO_TARBALL=${CHELSIO}.tar.gz
#CHELSIO_URL=https://s3.amazonaws.com/nyble-binary-driver-blobs/${CHELSIO_TARBALL}
CHELSIO_URL=http://192.168.5.250:10091/drivers/chelsio/${CHELSIO_TARBALL}
CHELSIO_PATCH=/root/chelsio.4.15.patch

###
# 

if [ -e "/etc/debian_version" ]; then
export KV=`dpkg -l  | grep linux-image- | grep -v meta | perl -lane 'print $F[1] =~ /linux-image-(.*)/'`
export KSV=`echo ${KV} | perl -lane 'printf $F[0] =~ /^(\d+\.\d+)/'`
export KP=/usr/src/linux-source-${KSV}
fi

if [ -e "/etc/redhat-release" ]; then
export KV=`rpm -qa | grep kernel | grep -v devel | grep -v headers | grep -v tools | perl -pe 's/kernel-(.*?)-1.x86_64/$1/'`
export KSV=`echo ${KV} | perl -lane 'printf $F[0] =~ /^(\d+\.\d+)/'`
export KP=/usr/src/kernels/${KV}
fi

echo KSV = ${KSV}
echo KP  = ${KP}
echo KV  = ${KV}
# 1st install Chelsio driver

if [ ${INSTALL_DRIVER} -eq 1]; then
export CXGB4=`find /lib/modules | grep cxgb4.ko`
mv ${CXGB4} ${CXGB4}.original
fi

pushd .
mkdir -p /tmp/cxgb
cd /tmp/cxgb
echo "nameserver 1.1.1.1" >> /etc/resolv.conf
curl ${CHELSIO_URL} > ${CHELSIO_TARBALL}
tar -zxf ${CHELSIO_TARBALL}

cd ${CHELSIO}

# have to apply patch!, or it won't build for 4.14 and beyond.
patch -p2 < ${CHELSIO_PATCH}

if [ ${INSTALL_DRIVER} -eq 1 ]; then
# NIC
make nic KDIR=/lib/modules/${KV}/build KVER=${KV}
cp -fv `find | grep cxgb4.ko$` ${CXGB4}
fi

# TOOLS
make tools KDIR=/lib/modules/${KV}/build KVER=${KV}
cp ./build/tools/cxgbtool/cxgbtool /usr/local/bin

if [ ${INSTALL_FIRMWARE} -eq 1 ]; then
# FW
pushd .
cd /lib/firmware 
rm -rf cxgb4
popd
mkdir -p /lib/firmware/cxgb4
cp -rv ./src/network/firmware/* /lib/firmware/cxgb4
cd /lib/firmware/cxgb4
ln -s t4fw-*.bin t4fw.bin
ln -s t5fw-*.bin t5fw.bin
ln -s t6fw-*.bin t6fw.bin
fi

depmod -a ${KV}

# 3rd clean up extraneous stuff (docs, etc.)
popd 
rm -rf /tmp/cxgb ${CHELSIO_PATCH} /root/install /root/kv.data


