#!/bin/bash -x

# Chelsio driver info
CHELSIO_REV=3.7.0.2
CHELSIO=ChelsioUwire-${CHELSIO_REV}
CHELSIO_TARBALL=${CHELSIO}.tar.gz
CHELSIO_URL=https://s3.amazonaws.com/nyble-binary-driver-blobs/${CHELSIO_TARBALL}
CHELSIO_PATCH=/root/chelsio.4.15.patch

###
# 

if [ -e "/etc/debian_version" ]; then
export KV=`dpkg -l  | grep linux-image- | grep -v meta | perl -lane 'print $F[1] =~ /linux-image-(.*)/'`
export KSV=`echo ${KV} | perl -lane 'printf $F[0] =~ /^(\d+\.\d+)/'`
export KP=/usr/src/linux-source-${KSV}
fi

if [ -e "/etc/redhat-release" ]; then
export KV=`rpm -qa | grep kernel | grep -v devel | grep -v headers | grep -v tools | perl -pe 's/kernel-(.*?)-1.x86_64/$1/'`
export KSV=`echo ${KV} | perl -lane 'printf $F[0] =~ /^(\d+\.\d+)/'`
export KP=/usr/src/kernels/${KV}
fi

echo KSV = ${KSV}
echo KP  = ${KP}
echo KV  = ${KV}
# 1st install Chelsio driver

export CXGB4=`find /lib/modules | grep cxgb4.ko`
mv ${CXGB4} ${CXGB4}.original

pushd .
mkdir -p /tmp/cxgb
cd /tmp/cxgb
wget ${CHELSIO_URL}
tar -zxf ${CHELSIO_TARBALL}

cd ${CHELSIO}

# have to apply patch!, or it won't build for 4.14 and beyond.
patch -p2 < ${CHELSIO_PATCH}

# NIC
make nic KDIR=/lib/modules/${KV}/build KVER=${KV}
cp -fv `find | grep cxgb4.ko$` ${CXGB4}a


# TOOLS
make tools KDIR=/lib/modules/${KV}/build KVER=${KV}
cp ./build/tools/cxgbtool/cxgbtool /usr/local/bin

# FW
#rm -rf /lib/firmware/cxgb4
#mkdir  /lib/firmware/cxgb4
#cp -rv ./src/network/firmware/* /lib/firmware/cxgb4


depmod -a


# 3rd clean up extraneous stuff (docs, etc.)
popd 
rm -rf /tmp/cxgb


